services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: springboot-todo
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: